### PR TITLE
fix(adapter): do not emit debug url unless in a browser

### LINKED ISSUE #262: Cannot read property 'origin' of undefined (NativeScript)
### Steps to reproduce
1. Set up NativeScript
2. `tns create project-name`
3. Select Angular
4. Select Hello World
5. `tns test init`
6. Select jasmine
7. Make a test fail -> change `/src/tests/example.ts` to:
```
// A sample Jasmine test
describe("A suite", function() {
  it("contains spec with an expectation", function() {
    expect(true).toBe(false);
  });
});
```
8. `tns test android`

### Expected behaviour
```
NativeScript / 29 (10; ONEPLUS A6003): Executed 0 of 1 SUCCESS (0 secs / 0 secs)
NativeScript / 29 (10; ONEPLUS A6003) A suite contains spec with an expectation FAILED
	Error: Expected true to be false.
	    at <Jasmine>
NativeScript / 29 (10; ONEPLUS A6003): Executed 1 of 1 (1 FAILED) (0.061 secs / 0.005 secs)
```
Output with karma-jasmine@2.0.1

### Actual behaviour
```
NativeScript / 29 (10; ONEPLUS A6003): Executed 0 of 1 SUCCESS (0 secs / 0 secs)
JS: NSUTR: this.error: An error was thrown in afterAll
JS: TypeError: Cannot read property 'origin' of undefined
JS:     at <Jasmine>
NativeScript / 29 (10; ONEPLUS A6003)  undefined at line undefined FAILED
	An error was thrown in afterAll
	TypeError: Cannot read property 'origin' of undefined
	    at <Jasmine>
NativeScript / 29 (10; ONEPLUS A6003): Executed 1 of 1 (1 FAILED) (0 secs / 0 secs)
```
Output with karma-jasmine@3.1.0

Probable error source in adapter.js at line 106:
```
function debugUrl (description) {
  // A link to re-run just one failed test case.
  return window.location.origin + '/debug.html?spec=' + encodeURIComponent(description)
}
```

### PR DESCRIPTION
**Pull request by johnjbarton**
Surprise: someone uses karma-jasmine with native=script.
Fixes #262

### CODE REVIEW

File: src/adapter.js [hunk 1]
```diff
@@ -247,8 +247,10 @@ function KarmaReporter (tc, jasmineEnv) {
         result.log.push(formatFailedStep(steps[i]))
       }
 
-      // Report the name of fhe failing spec so the reporter can emit a debug url.
-      result.debug_url = debugUrl(specResult.fullName)
+      if (window && window.location && window.location.origin) {
```
Comment (kyliau) [inline src/adapter.js]: Are we assuming that this code will run in Node?
According to #262 that doesn't seem like the case.
`window` is still defined, but window.location is not, because the error message was
```
Cannot read property 'origin' of undefined
```
when trying to access `window.location.origin`

I'm asking because the check for 'window' done this way will actually throw a ReferenceError in Node

Comment (johnjbarton) [reply src/adapter.js]: Of course I don't know how this error can happen. But you are completely correct, so I used `typeof`.
